### ISSUE TITLE
show me this error

### ISSUE THREAD

**Issue by ahammamlho** [codenameakshay/image-editor#6]
Exception has occurred.
_AssertionError ('package:extended_image_library/src/extended_image_provider.dart': Failed assertion: line 34 pos 12: 'cacheRawData': you should set [ExtendedImageProvider.cacheRawData] to true, if you want to get rawImageData from provider.)

this  final Uint8List img = state.rawImageData;

plz help me

**Comment by codenameakshay** [comment]
Please explain the error more, include logs and flutter doctor.
