### ISSUE TITLE
File is not being updated after crop.

### ISSUE THREAD

**Issue by guihackmann** [codenameakshay/image-editor#7]
Hi,

I followed all your steps, but can't seem to get the File image updated.
When I run crop, the raw/original image (without any editions that I made) gets sent to the save screen.

How to update the original File with the editions that were made?

**Comment by SarveshSub** [comment]
How did you fix this? I am having the same issue.

**Comment by SarveshSub** [comment]
> Hi,
> 
> I followed all your steps, but can't seem to get the File image updated. When I run crop, the raw/original image (without any editions that I made) gets sent to the save screen.
> 
> How to update the original File with the editions that were made?

I am having the same issue.
